# Nome da Actions:
name: Snake Game

# Controlador do tempo que sera feito a atualização dos arquivos.
on:
  schedule:
    # Será atualizado a cada 5 horas.
    - cron: "0 */5 * * *"

  # Permite executar na lista de Actions (utilizado para testes de build).
  workflow_dispatch:

# Permissões necessárias para permitir push no repositório
permissions:
  contents: write

# Regras
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Checks repo under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

    # Repositorio que será utilizado para gerar os arquivos.
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: taisfonseca # Seu usuario
          outputs: |
            dist/github-contribution-grid-snake.gif
            dist/github-contribution-grid-snake.svg

      - run: git status

      # Para as atualizações.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true

      - uses: crazy-max/ghaction-github-pages@v4
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
