name: Snake Game

on:
  schedule:
    # Executa a cada 5 horas
    - cron: "0 */5 * * *"
  # Permite execução manual
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      # Faz checkout do repositório
      - name: Checkout
        uses: actions/checkout@v4

      # Gera a cobrinha
      - name: Generate Snake
        uses: Platane/snk@v3.2.0
        with:
          github_user_name: taisfonseca
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg
            dist/github-contribution-grid-snake.gif

      # Publica os arquivos na branch "output"
      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
